
services:

  auth-service-db:
    image: postgres:latest
    container_name: auth-db
    restart: always
    environment:
      POSTGRES_DB: ${AUTH_DB_NAME}
      POSTGRES_USER: ${AUTH_DB_USER}
      POSTGRES_PASSWORD: ${AUTH_DB_PASSWORD}
    ports:
      - "${AUTH_DB_PORT}:5432"
    networks:
      - internal
    volumes:
      # Named volume for DB, delete before each run for fresh DB
      - auth-service-db-data:/var/lib/postgresql/data

  auth-service:
    build:
      context: .
      dockerfile: Dockerfile
      # Force rebuild ignoring cache
      cache_from: []
    container_name: auth-service
    ports:
      - "4005:4005"
    environment:
      SERVER_PORT: ${AUTH_SERVICE_SERVER_PORT}
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
      SPRING_JPA_HIBERNATE_DDL_AUTO: ${SPRING_JPA_HIBERNATE_DDL_AUTO}
      SPRING_SQL_INIT_MODE: ${SPRING_SQL_INIT_MODE}
      JWT_SECRET: ${JWT_SECRET}
    networks:
      - internal
    depends_on:
      - auth-service-db

networks:
  internal:

volumes:
  # Named volume for database
  auth-service-db-data: